apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: guidellm-output-pvc
  namespace: llm-d
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  storageClassName: standard
  volumeMode: Filesystem
