apiVersion: v1
kind: ConfigMap
metadata:
  name: run-config
data:
  config.yaml: |
    tool_groups:
    - toolgroup_id: builtin::websearch
      provider_id: tavily-search
    - toolgroup_id: builtin::rag
      provider_id: rag-runtime
    - toolgroup_id: builtin::code_interpreter
      provider_id: code-interpreter
    - toolgroup_id: mcp::openshift
      provider_id: model-context-protocol
      mcp_endpoint:
        uri: "http://ocp-mcp-server:8000/sse"
    - toolgroup_id: mcp::ansible
      provider_id: model-context-protocol
      mcp_endpoint:
        uri: "http://ansible-mcp-server:8000/sse"
    - toolgroup_id: mcp::slack
      provider_id: model-context-protocol
      mcp_endpoint:
        uri: "http://slack-mcp-server:8000/sse"
    - toolgroup_id: mcp::github
      provider_id: model-context-protocol
      mcp_endpoint:
        uri: "http://github-mcp-server:8000/sse"
