apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../llama-stack
  #- ../../safety-model # Requires GPUs
  - ../../streamlit-client
  - ../../notebooks

  # mcp-servers resources
  # - ../../mcp-servers/ansible-mcp
  # - ../../mcp-servers/custom-mcp
  # - ../../mcp-servers/github-mcp
  - ../../mcp-servers/openshift-mcp
