name: Generate Notebooks ConfigMap

on:
  push:
    branches:
      - main
    paths:
      - 'demos/rag_agentic/notebooks/**.ipynb'
  pull_request:
    branches:
      - main
  workflow_dispatch:  # Allow manual triggering

jobs:
  generate-configmap:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r utils/requirements.txt

      - name: Execute dynamic_notebooks.py script
        run: |
          python utils/dynamic_notebooks.py

#      - name: Commit changes
#        run: |
#          git config --global user.name 'GitHub Actions'
#          git config --global user.email 'github-actions@github.com'
#          git add kubernetes/
#          git commit -m "Auto-generate notebook ConfigMap and deployment YAML" || echo "No changes to commit"
#          git push
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
